Repository Kauavitorio/Squash_App, pull requests merged in 2021-07, with the labels that each got.

#5 Update Design Squash (#5)
  Design/Project - Squash.fig
  Design/icons/send-message.png
  Design/img/back-first-access.png
  Design/img/back-login.png
  Design/img/back-splash.png
  Design/logo/logo-icon-png.png
Labels: design

#6 Create WebView and low cache (#2)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/kaua/squash/Activitys/MessageActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/WebActivity.java
  app/src/main/java/dev/kaua/squash/Adapters/Chat/MessageAdapter.java
  app/src/main/res/drawable/ic_not_secure_lock.xml
  app/src/main/res/drawable/ic_secure_lock.xml
  app/src/main/res/layout/activity_message.xml
  app/src/main/res/layout/activity_web.xml
  app/src/main/res/layout/adapter_chat_item_left.xml
  app/src/main/res/layout/adapter_chat_item_right.xml
  app/src/main/res/layout/adapter_start_chat.xml
  app/src/main/res/menu/menu_web.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: code

#8 Creation New Post, Edit Profile and Search Screens. (#8)
  Design/Project - Squash.fig
  Design/banner/Banner - River.fig
  Design/banner/Banner - River.pdf
  Design/banner/Banner - Squash.fig
  Design/banner/Banner - Squash.jpg
  Design/banner/Banner - Squash.pdf
  Design/banner/Banner-River.jpg
  Design/icons/close-line-dark.png
  Design/icons/close-line-light.png
  Design/icons/image-add-fill.png
  Design/icons/video-fill.png
Labels: design

#9 Posts (#9)
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/java/dev/kaua/squash/Activitys/ComposeActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/EditProfileActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/SignUpActivity.java
  app/src/main/java/dev/kaua/squash/Adapters/Posts_Adapters.java
  app/src/main/java/dev/kaua/squash/Adapters/Profile/Profile_Image.java
  app/src/main/java/dev/kaua/squash/Data/Account/AccountServices.java
  app/src/main/java/dev/kaua/squash/Data/Post/Actions/RecommendedPosts.java
  app/src/main/java/dev/kaua/squash/Data/Post/AsyncLikes_Posts.java
  app/src/main/java/dev/kaua/squash/Data/Post/DtoPost.java
  app/src/main/java/dev/kaua/squash/Data/Post/PostServices.java
  app/src/main/java/dev/kaua/squash/Fragments/MainFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/ProfileFragment.java
  app/src/main/java/dev/kaua/squash/LocalDataBase/DaoPosts.java
  app/src/main/java/dev/kaua/squash/Tools/Methods.java
  app/src/main/res/drawable/background_signin.png
  app/src/main/res/drawable/custom_edit_compose.xml
  app/src/main/res/drawable/custom_edit_register_new.xml
  app/src/main/res/drawable/ic_add_img.png
  app/src/main/res/drawable/ic_three_dots.png
  app/src/main/res/layout/activity_compose.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_share_content.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/adapter_include_main.xml
  app/src/main/res/layout/adapter_posts.xml
  app/src/main/res/layout/adapter_sheet_menu_post_action.xml
  app/src/main/res/layout/fragment_users.xml
  app/src/main/res/raw/halloween_pumpkin_black_cat.json
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: code

#11 Create comment on post (#11)
  app/src/main/java/dev/kaua/squash/Activitys/ComposeActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/MainActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/MessageActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/PostDetailsActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/SplashActivity.java
  app/src/main/java/dev/kaua/squash/Adapters/Chat/UserChatAdapter.java
  app/src/main/java/dev/kaua/squash/Adapters/Comments_Adapters.java
  app/src/main/java/dev/kaua/squash/Adapters/Posts_Adapters.java
  app/src/main/java/dev/kaua/squash/Adapters/SearchItemArrayAdapter.java
  app/src/main/java/dev/kaua/squash/Data/Account/AsyncUser_Search.java
  app/src/main/java/dev/kaua/squash/Data/Account/DtoAccount.java
  app/src/main/java/dev/kaua/squash/Data/Post/Actions/RecommendedPosts.java
  app/src/main/java/dev/kaua/squash/Data/Post/AsyncComments_Posts.java
  app/src/main/java/dev/kaua/squash/Data/Post/AsyncLikes_Posts_Comment.java
  app/src/main/java/dev/kaua/squash/Data/Post/DtoPost.java
  app/src/main/java/dev/kaua/squash/Data/Post/PostServices.java
  app/src/main/java/dev/kaua/squash/Fragments/Chat/ChatsFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/ChatFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/ProfileFragment.java
  app/src/main/java/dev/kaua/squash/LocalDataBase/DaoChat.java
  app/src/main/java/dev/kaua/squash/LocalDataBase/DaoPosts.java
  app/src/main/java/dev/kaua/squash/Notifications/MyFirebaseMessaging.java
  app/src/main/java/dev/kaua/squash/Security/Login.java
  app/src/main/java/dev/kaua/squash/Tools/Methods.java
  app/src/main/java/dev/kaua/squash/Tools/Warnings.java
  app/src/main/java/dev/kaua/squash/Tools/myTimeHelper.java
  app/src/main/res/drawable/custom_edit_register_new.xml
  app/src/main/res/drawable/ic_comment.png
  app/src/main/res/drawable/ic_pencil.png
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_message.xml
  app/src/main/res/layout/activity_post_details.xml
  app/src/main/res/layout/adapter_comments.xml
  app/src/main/res/layout/adapter_comum_alert_need_login.xml
  app/src/main/res/layout/adapter_posts.xml
  app/src/main/res/layout/adapter_search_layout.xml
  app/src/main/res/layout/adapter_user_items.xml
  app/src/main/res/layout/fragment_activity_profile.xml
  app/src/main/res/layout/fragment_chats.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: code

#12 Update version (#12)
  app/build.gradle
  app/src/main/java/dev/kaua/squash/Activitys/MessageActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/ShareContentActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/SplashActivity.java
  app/src/main/java/dev/kaua/squash/Adapters/Chat/MessageAdapter.java
  app/src/main/java/dev/kaua/squash/Adapters/Chat/UserChatAdapter.java
  app/src/main/java/dev/kaua/squash/Data/Account/DtoAccount.java
  app/src/main/java/dev/kaua/squash/Data/Message/Chatslist.java
  app/src/main/java/dev/kaua/squash/Data/System/DtoSystem.java
  app/src/main/java/dev/kaua/squash/Fragments/Chat/ChatsFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/MainFragment.java
  app/src/main/java/dev/kaua/squash/LocalDataBase/DaoChat.java
  app/src/main/java/dev/kaua/squash/Notifications/Data.java
  app/src/main/java/dev/kaua/squash/Notifications/MyFirebaseMessaging.java
  app/src/main/java/dev/kaua/squash/Tools/Methods.java
  app/src/main/java/dev/kaua/squash/Tools/MyPrefs.java
  app/src/main/java/dev/kaua/squash/Tools/Warnings.java
  app/src/main/res/layout/adapter_appneedupdate.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/strings.xml
Labels: code, documentation

#13 Messages and build (#13)
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/kaua/squash/Activitys/MessageActivity.java
  app/src/main/java/dev/kaua/squash/Activitys/SplashActivity.java
  app/src/main/java/dev/kaua/squash/Adapters/Chat/MessageAdapter.java
  app/src/main/java/dev/kaua/squash/Adapters/Posts_Adapters.java
  app/src/main/java/dev/kaua/squash/Data/Account/AccountServices.java
  app/src/main/java/dev/kaua/squash/Data/Post/Actions/RecommendedPosts.java
  app/src/main/java/dev/kaua/squash/Data/Post/AsyncRecommended_Posts_feed.java
  app/src/main/java/dev/kaua/squash/Data/Post/DtoPost.java
  app/src/main/java/dev/kaua/squash/Firebase/ConfFirebase.java
  app/src/main/java/dev/kaua/squash/Fragments/Chat/ChatsFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/Chat/UsersFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/ChatFragment.java
  app/src/main/java/dev/kaua/squash/Fragments/SearchFragment.java
  app/src/main/java/dev/kaua/squash/LocalDataBase/DaoFollowing.java
  app/src/main/java/dev/kaua/squash/Notifications/APIService.java
  app/src/main/java/dev/kaua/squash/Tools/Methods.java
  app/src/main/java/dev/kaua/squash/Tools/PatternEditableBuilder.java
  app/src/main/res/drawable/background_media_action.xml
  app/src/main/res/drawable/background_right_msg.xml
  app/src/main/res/drawable/cute_pumpkin.png
  app/src/main/res/drawable/ic_close_simple_white.xml
  app/src/main/res/drawable/ic_video.png
  app/src/main/res/drawable/no_message_background.xml
  app/src/main/res/layout/activity_message.xml
  app/src/main/res/layout/adapter_posts.xml
  app/src/main/res/layout/adapter_sheet_media_action.xml
  app/src/main/res/layout/adapter_user_items.xml
  app/src/main/res/layout/fragment_activity_chat.xml
  app/src/main/res/layout/fragment_activity_search.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, code
